# Generated by Django 3.2.7 on 2021-09-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagories',
            name='image',
            field=models.TextField(max_length=1202),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.TextField(max_length=1202),
        ),
    ]
