# Generated by Django 3.2.7 on 2021-09-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210920_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagories',
            name='image',
            field=models.ImageField(upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='posts/'),
        ),
    ]
