# Generated by Django 3.2.7 on 2021-09-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210920_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
