# Generated by Django 3.2.7 on 2021-09-21 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210920_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='colors',
        ),
    ]
